[package]
name = "infr_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
infr_transfer = { path = "../infr_transfer", features = ["server"] }
infr_layout = { path = "../infr_layout" }
infr_solver = { path = "../infr_solver" }
log = "0.4.29"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["full"] }
toml = "0.9.11"
tracing-subscriber = "0.3.22"
mlua = { version = "0.11.5", features = ["luajit", "send"] }
