[package]
name = "infr_layout"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.11.6", features = ["async", "luajit", "macros", "mlua_derive", "send"] }
infr_solver = { path = "../infr_solver", features = ["mlua"] }
infr_macros = { path = "../infr_macros" }
sha256 = { version = "1.6.0" }
log = "0.4.29"
