[package]
name = "infr_main"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = [
  "2d",
  "debug",
  "dynamic_linking",
  "wayland",
] }
bevy_ehttp = "0.7.0"
infr_client = { path = "../infr_client" }
infr_level = { path = "../infr_level" }
infr_res = { path = "../infr_res" }
